parameters:
  fieldSize: 10
services:
  gameRepository:
    class: kufi\BattleshipBundle\Model\GameRepository
    arguments: [@doctrine.orm.entity_manager]
  
  singleplayerController:
    class: kufi\BattleshipBundle\Controller\SingleplayerController
    arguments: [@gameRepository, @session, %fieldSize%]