services:
  gameRepository:
    class: kufi\BattleshipBundle\Model\GameRepository
    arguments: [@doctrine.orm.entity_manager]
  userRepository:
    class: kufi\BattleshipBundle\Model\UserRepository
    arguments: [@doctrine.orm.entity_manager]